spring.application.name=Husle Hard

# Configuration de la base de donnée
spring.datasource.url=jbdc:postgresql://${DB_HOST}:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
# "update" va créer les tables automatiquement si elles n'existent pas
# et modifier les colonnes si tu changes ton code Java.

spring.jpa.hibernate.ddl-auto=update


# Affiche les requêtes SQL dans la console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecte pour PostgreSQL (Optimise le SQL généré)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialecte.PostgreSQLDialect